### ISSUE TITLE
Sort by rank appears to have broken

### ISSUE THREAD

**Issue by jndizoglio** [jodelahithit/runelite-plugins#10]
I used to use this plugin, and it worked fine, but I reinstalled runelite and I think it broke the plugin I can no longer sort by rank

**Comment by jodelahithit** [comment]
Thanks for your report. Unfortunately this is the first time I've heard of this happening and I can't seem to replicate it. I've asked a few users to test it and they reported that sorting by rank still works as intended.

I'm not aware of any plugin related issues when reinstalling Runelite. Perhaps you could try to reinstall the plugin in the plugin hub? If that doesn't work I suggest asking for help in the Runelite Discord server. Perhaps they know what's up.

**Comment by jndizoglio** [comment]
Thanks for trying to replicate my issue. It currently just spam refreshed endlessly and makes it impossible to read. I guess I will just stick to sorting by name

**Comment by jodelahithit** [comment]
I'll ask some more users to check if it's working as intended for them. Could you perhaps send me a video of the issue? That might be helpful.
