### ISSUE TITLE
Skilling Notifications - 2 suggestions/requests: Noti colour fade-in/out, Walking delay detect yellow x clicks w/o movement

### ISSUE THREAD

**Issue by UnIockables** [jodelahithit/runelite-plugins#12]
Thank you for the plugin, it really does wonders for afking :)

Main request:

Could there be an option to add an option for a fade-in and fade-out animation to the notification colour, with a configurable fade time?

Second request: (this suggestion is less important but thought I'd ask anyways, if not possible/too difficult don't worry about it)

Could the 'Walking delay' detect a yellow x click on your current (or unreachable) tile to reset the delay timer (a 'walk here' click without any movement)?

**Comment by jodelahithit** [comment]
Hey there, thank you for the kind words and suggestions. I've added both your requests to the plugin. Once the pull request has been accepted the new features will be available in Runelite!
