### ISSUE TITLE
Sort by rank does nothing

### ISSUE THREAD

**Issue by JoRouss** [jodelahithit/runelite-plugins#2]
The sorting by name and world seems to work.

Sorting by rank does not.

**Comment by jodelahithit** [comment]
Thanks for bringing this to my attention. I've received another report of this happening so I've already started looking into it! Next update should hopefully contain a fix.
Are you using the plugin on mac or windows?

**Comment by jodelahithit** [comment]
I just released a new version which adds some debugging tools for this issue. When you start the the plugin and select sort by rank, it should start randomizing the names rapidly if anything goes wrong.
If this is the case, could you please send me your Runelite log located in "C:\Users{user}.runelite\logs"? Thanks!
Feel free to contact me on Discord if that's easier for you: Jodelahithit#0001

**Comment by jodelahithit** [comment]
The issue should be fixed in update 1.3 which released yesterday. Feel free to contact me if you're still experiencing the issue!
