### ISSUE TITLE
Crystal 2H Felling Doesn't Register

### ISSUE THREAD

**Issue by Bass-Music** [jodelahithit/runelite-plugins#20]
The plugin perceives me as idle as soon as I start woodcutting with a Crystal 2H felling axe. When I switch to an infernal axe it works as intended.

**Comment by erwinvc** [comment]
Functionality for the 2H axes has already been added to the plugin but unfortunately we have to wait for the Runelite team to accept the pull request. It's been open for quite a while so I expect the changes to be available soon.

**Comment by Bass-Music** [comment]
Thank you!
