### ISSUE TITLE
[Skilling Notifications] Suggestion: Audio

### ISSUE THREAD

**Issue by Looodon** [jodelahithit/runelite-plugins#21]
Hey!
I sometimes play with the window minimized when I'm afk combat training, I set it up so that when my character stops fighting back the screen goes red, which is perfect, but I can't tell that it's red when it's minimized. I think having the option to use Runelite's sound notifications might help with that.
Thank you! :D

**Comment by erwinvc** [comment]
Great suggestion! I've added the functionality so it'll be added to the plugin once I have a few more noteworthy updates.

**Comment by Looodon** [comment]
Alright, excited to try it out once it's out. Thank you! ^_^

**Comment by Looodon** [comment]
Hey @erwinvc :) Just checking in, It looks like this feature was added in a commit 4 months ago. Any chance you have a timeframe for publishing the update with this included? Thanks!

**Comment by erwinvc** [comment]
Apologies for not getting back to you sooner. I had hoped to be able to work on a few more updates but other projects got in the way. I've created a [pull request](https://github.com/runelite/plugin-hub/pull/5698) so the plugin should be updated with this feature somewhere in the next few days.
