### ISSUE TITLE
Skilling Notifications Flash Option

### ISSUE THREAD

**Issue by septicsalmon** [jodelahithit/runelite-plugins#3]
Possible to add a toggle to make the skiling notification flash instead of solid colour?

**Comment by jodelahithit** [comment]
Absolutely! I can do that tonight so expect an update with this feature soon.

**Comment by jodelahithit** [comment]
Opened a pull request with the update so it should be available as soon as the request is accepted.

**Comment by septicsalmon** [comment]
Very cool, thanks!
