### ISSUE TITLE
Making Glass At Furnace XP Drops Don't Count

### ISSUE THREAD

**Issue by jevonsp** [jodelahithit/runelite-plugins#6]
Just encountered that making glass at a furnace doesn't count for turning off the idle notification. 

love the plugin!!

e; while im here, can firemaking be added please? thanks :)

**Comment by jodelahithit** [comment]
Thanks for the heads up, I'll take a look at the glass issue and I'll add firemaking while I'm at it!

**Comment by jodelahithit** [comment]
I opened the pull request so it should be in Runelite within a few days. Thanks for the feedback!
